<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <script>
      function increase(number) {
        const promise = new Promise((resolve, reject) => {
          setTimeout(() => {
            const result = number + 10;

            if (result > 50) {
              const e = new Error("NumberTooBig");

              return reject(e);
            }

            resolve(result);
          }, 1000);
        });

        return promise;
      }

      console.log(increase(0));

      async function run() {
        try {
          // async-await을 통해 Promise 객체가 아닌 비동기 동작이 끝난 결과가 담기게 됨.
          let result = await increase(0);
          console.log(result);

          result = await increase(result);
          console.log(result);

          result = await increase(result);
          console.log(result);

          result = await increase(result);
          console.log(result);

          result = await increase(result);
          console.log(result);

          result = await increase(result);
          console.log(result);
        } catch (e) {
          console.log(e, "가 발생했다!!");
        }
      }

      run();
    </script>
  </body>
</html>
